..............This part is done using sklearn..............

In [ ]:
import numpy as np
from sklearn.datasets import load_diabetes #scikit-learn is a machine learning library in Python that provides various tools for data analysis and modeling. The load_diabetes function is used to load the diabetes dataset, which is a commonly used dataset for regression tasks.

In [4]:
X,y = load_diabetes(return_X_y=True)

In [5]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
X.shape

(442, 10)

In [7]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)


Here is a breakdown of the specific arguments passed into the function:

X, y: These are the feature matrix (X) and the target vector (y) that you previously loaded. They are passed in together so that their rows are shuffled and split in sync, ensuring that each feature row in X still matches up with its correct target label in y.

test_size=0.2: This determines the proportion of the dataset to include in the test split. Passing 0.2 allocates 20% of the data for testing, leaving the remaining 80% for training the model.

random_state=2: Before splitting, the function randomly shuffles the data. Providing a specific integer seed (like 2) controls this randomization process. This ensures reproducibility; every time you run this cell, the data will be split in exactly the same way. If random_state=None (the default), the split is different each run; any integer can be used as a seed (common choices are 0, 1, or 42).

In [9]:
print(X_train.shape)
print(y_train.shape)

(353, 10)
(353,)


In [ ]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()

In [12]:
reg.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = reg.predict(X_test)
print(y_pred)

[154.1213881  204.81835118 124.93755353 106.08950893 258.5348576
 256.3310074  118.75087616 119.52440696 101.50816735 190.54048661
 141.70656811 172.51883961 174.33861649 134.80942706 294.13994537
  94.11798038 211.97059795 156.49579378 134.21000428 119.62664644
 148.87842251 165.00873409 151.10021038 176.04063756 133.27769647
 221.29555392 197.17324941  96.1577688   50.26012711 230.48580317
 242.06073866 114.11129218  67.07532417  94.52943825 201.21415375
 167.05136201 159.881268   192.78746659 114.49551325 233.48234551
 140.82563045 121.0680409  192.27480772 191.12738845 179.16865788
 148.34935601 163.47414622 276.81647884 100.17926432 164.10555298
 255.80762189 136.9466204  152.37503699 107.92237882 194.21924678
  77.34670792 118.50482479  68.38335763 154.29258529 162.48840259
 168.36788326 156.87790322  97.14191797 238.1671215  145.46179904
 117.65702433 168.88784311 198.38683887 118.24053714 124.64552812
 223.17700368 200.63012386 129.54414666 158.1584765  154.332565
 114.47070769

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(y_test, y_pred)

0.4399338661568968

What it is: r2_score computes the coefficient of determination for a regression model — a single-number summary of how well predictions match the true targets.

Formula: R² = 1 − (Σ(y_true − y_pred)²) / (Σ(y_true − y_mean)²). It measures the proportion of variance in y_true explained by the model.

Range & meaning: 1.0 = perfect fit; 0.0 = model is as good as predicting the mean; negative values = model is worse than predicting the mean. Higher is better.

When to use: Use for regression tasks to compare models or to report goodness-of-fit. Be cautious with outliers, non-linear relationships, or when target variance is tiny.

Usage example: r2_score(y_test, y_pred) returns the R² for those arrays.

In [18]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [19]:
reg.intercept_

np.float64(151.88331005254167)

..............This part is done using gradient descent..............

In [25]:
class MultipleLinearRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1) #added a column of 1s to the left of X_train for the intercept term
        
        #calculate the coefficients
        betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        

    def predict(self, X_test):
        y_pred = np.dot(X_test, self.coef_) + self.intercept_
        return y_pred

In [26]:
mlr = MultipleLinearRegression()

In [27]:
mlr.fit(X_train, y_train)

In [28]:
mlr_y_pred = mlr.predict(X_test)
print(mlr_y_pred)

[154.1213881  204.81835118 124.93755353 106.08950893 258.5348576
 256.3310074  118.75087616 119.52440696 101.50816735 190.54048661
 141.70656811 172.51883961 174.33861649 134.80942706 294.13994537
  94.11798038 211.97059795 156.49579378 134.21000428 119.62664644
 148.87842251 165.00873409 151.10021038 176.04063756 133.27769647
 221.29555392 197.17324941  96.1577688   50.26012711 230.48580317
 242.06073866 114.11129218  67.07532417  94.52943825 201.21415375
 167.05136201 159.881268   192.78746659 114.49551325 233.48234551
 140.82563045 121.0680409  192.27480772 191.12738845 179.16865788
 148.34935601 163.47414622 276.81647884 100.17926432 164.10555298
 255.80762189 136.9466204  152.37503699 107.92237882 194.21924678
  77.34670792 118.50482479  68.38335763 154.29258529 162.48840259
 168.36788326 156.87790322  97.14191797 238.1671215  145.46179904
 117.65702433 168.88784311 198.38683887 118.24053714 124.64552812
 223.17700368 200.63012386 129.54414666 158.1584765  154.332565
 114.47070769

In [29]:
r2_score(y_test, y_pred)

0.4399338661568968

In [30]:
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [31]:
mlr.intercept_

np.float64(151.88331005254165)